fcsonline/drill

src/expandable/include.rs
Just adding some info when config does not have a `plan` node; cheers
ref https://github.com/fcsonline/drill/issues/3
=> Show failing on plan missing on config

src/interpolator.rs
Spent a long time trying to figure out why identifiers like {{addr1}} and
{{zip4} wouldn't work.
=> Allow everything but first character of an identifier to be a number

README.md, src/actions/assign.rs, src/actions/request.rs, src/benchmark.rs, src/config.rs, src/main.rs
Shows duration in summary stats in nanoseconds for those who want to squeeze know it. Running benchmark against the testserver with `-sqn` yields:
```
Threads 20
Iterations 3
Rampup 2
Base URL http://localhost:9000
Fetch organizations       Total requests            60
Fetch organizations       Successful requests       60
Fetch organizations       Failed requests           0
Fetch organizations       Median time per request   119034191ns
Fetch organizations       Average time per request  119306601ns
Fetch organizations       Sample standard deviation 7650892ns
...
Fetch sub comments        Total requests            60
Fetch sub comments        Successful requests       0
Fetch sub comments        Failed requests           60
Fetch sub comments        Median time per request …
```
=> Nanoseconds

README.md, src/actions/request.rs, src/benchmark.rs, src/config.rs, src/main.rs
Adds summary statistics per named job and adds a quiet option. I.e. running drill with `-sq` on test benchmark results in 
```
Threads 20
Iterations 3
Rampup 2
Base URL http://localhost:9000
Fetch user from assign    Total requests            60
Fetch user from assign    Successful requests       60
Fetch user from assign    Failed requests           0
Fetch user from assign    Median time per request   114ms
Fetch user from assign    Average time per request  117ms
Fetch user from assign    Sample standard deviation 10ms
...
Fetch account             Total requests            60
Fetch account             Successful requests       60
Fetch account             Failed requests           0
Fetch account             Median time per request   111ms
Fetch account             Average time per …
```
=> Stats per job

SYNTAX.md, example/benchmark.yml, src/expandable/include.rs, src/expandable/mod.rs, src/expandable/multi_iter_request.rs
Adds a support for a generator of numeric item ids from an iterator. Simply specify `with_items_range:` in the config with numeric values for start, step, stop. Each value is optional and will default to 1.
So, for your example valid options are
```yaml
- name: Fetch some users by iter
request:
url: /api/users/{{ item }}
with_items_range:
start: 70
step: 5
stop: 76
```
or
```yaml
- name: Fetch some users by iter
request:
url: /api/users/{{ item }}
with_items_range:
stop: 3
```
=> with_items_range

SYNTAX.md, example/benchmark.yml, src/expandable/multi_csv_request.rs, src/reader.rs
In the configuration file, allow new way specify item csv file and override
default csv quote character.  This is necessary for (possibly bad) csv files
that have single-quoted fields that contain commas.
=> First draft - Allow override of csv quote value

README.md, src/actions/request.rs
Increases robustness on connection refused errors, which may occur in overload scenarios. At the moment this results in a panic fail of the whole bench. With this change it will be converted to a 520 error and the bench continues.
=> Return 520 on bad connection

example/throughput.yml, src/actions/request.rs, src/interpolator.rs
I fixed two small performance issues:
- Avoid interpolator if there are no interpolations
- Avoid SSL initialization if is not `htttps`
Other:
- Extracted relative path resolver from interpolator
=> Improve general performance

README.md, src/actions/request.rs, src/benchmark.rs, src/config.rs, src/expandable/multi_csv_request.rs, src/expandable/multi_iter_request.rs, src/expandable/multi_request.rs, src/interpolator.rs, src/main.rs
After this https://github.com/fcsonline/drill/pull/41 we removed a panic when an interpolation didn't exist.  After rethinking the behavior about missing interpolations and I'm not sure about defaulting to empty string if previous requests failed. It can induce a wrong URL construction with an unexpected result.
This PR adds a new command flag called `relaxed-interpolations` to be opt-in for this behavior.
=> Relaxed interpolations

Cargo.lock, Cargo.toml, example/server/server.js, example/throughput.yml, src/actions/assign.rs, src/actions/mod.rs, src/actions/request.rs, src/benchmark.rs
KeepAlive is one of the most interesting features to improve the throughput of `drill`. We will reuse a Client instance per domain to be able to reuse the connection.
=> Add Keep Alive functionality

Cargo.lock, Cargo.toml, README.md, example/benchmark.yml, src/actions/request.rs, src/interpolator.rs
Some users like @mario-s in issue #50 want to have access to headers from previous requests to be able to propagate them in the next ones. Right now we only store the body of the requests.
This PR adds this functionality. It breaks compatibility with the previous syntax but I think the change worth it.
This is syntax has changed in terms of how to access body content:
```yaml
---
threads: 1
base: 'http://localhost:3000'
iterations: 1
plan:
- name: Fetch account headers
request:
url: /api/account
assign: foo
- name: Dynamic Custom headers
request:
url: /api/messages
headers:
X-Foo: Bar {{ foo.account_id }}
```
Now it will be like this:
```yaml
- name: Dynamic Custom headers
request:
url: /api/messages
headers:
X-Foo: Bar {{ foo.headers.token }}
X-Bar: Bar {{ foo.body.account_id }}
```
=> Add support to headers in assign

src/actions/assign.rs, src/actions/delay.rs, src/actions/mod.rs, src/actions/request.rs
Many users have problem trying to setup a benchmark with interpolations.
A common use case is:
```yaml
- name: Fetch user
request:
url: {{ memory.body.remote_url }}
```
This is an invalid payload because those curly brackets are valid YAML
syntax for hashes and drill expects a string there. To solve this, the
user needs wrap interpolation with quotes.
This commit improves the shown message when this happens.
=> Handle better misconfiguration

Cargo.toml, src/main.rs
When you ask for request `stats`, the order of requests is not preserved because we do a group of reports. This PR preserves this order for better usability.
=> Preserve the order of groups of requests

.travis.yml, Cargo.lock, README.md, SYNTAX.md, example/benchmark.yml, example/comments.yml, example/cookies.yml, example/delay.yml, example/headers.yml, example/iterations.yml, example/subcomments.yml, example/throughput.yml, src/actions/assign.rs, src/actions/delay.rs, src/actions/mod.rs, src/actions/request.rs, src/benchmark.rs, src/config.rs, src/expandable/include.rs, src/expandable/multi_csv_request.rs, src/expandable/multi_iter_request.rs, src/expandable/multi_request.rs, src/main.rs
Since we introduced `async`, the concurrency model of drill has changed a bit. The number of threads is less important. Also, in this PR 
https://github.com/fcsonline/drill/pull/55, we introduced a new parameter to choose how many concurrent iterations we wanted to execute at the same time, but this number was affecting the total number of requests was going to execute `drill` in total. For this reason, I wanted to simplify all this and achieve a place where:
- The user only choose the number of iteration to be executed. `iterations` parameter
- Number of concurrent iterations during the tests. `concurrency` parameter
This PR fixes all this.
On the other hand, this PR also computes the duration of the test only during the futures resolutions and not counting the preparation (building the …
=> Fix concurrency and iterations parameters

README.md, src/expandable/include.rs, src/expandable/multi_csv_request.rs, src/expandable/multi_iter_request.rs, src/expandable/multi_request.rs, src/interpolator.rs
There are some benchmark plan properties that don't support
interpolations because they are used during the plan expansion. They
belong to the bootstrap process and not to the runtime one.
Related https://github.com/fcsonline/drill/issues/94
=> Avoid interpolations in the bootstrap process

Cargo.lock, Cargo.toml
This commit add an explicit dependancy to "openssl-sys" and a "vendored
feature to allow cross compilation for x86_64-unknown-linux-musl
platform.
This allow single binary Docker image builds.
=> Fix building for x86_64-unknown-linux-musl

README.md, example/benchmark.yml, example/iterations.yml, src/actions/assert.rs, src/actions/mod.rs, src/expandable/include.rs
Adding the capability to assert variables during a test plan.
```yml
- name: Assert values
assert:
key: bar
value: "2"
- name: Assert values from responses
assert:
key: previous_request.body.manager_id
value: "73"
```
=> Assert values

README.md, example/benchmark.yml, src/actions/assert.rs, src/actions/exec.rs, src/actions/mod.rs, src/expandable/include.rs
Trying to cover the common use case of executing OS commands during a test plan, mentioned here: https://github.com/fcsonline/drill/issues/113
=> Add the capability to execute OS commands

Cargo.lock, Cargo.toml, src/main.rs
Instead of computing the statistical summary manually this commit makes
use of the HDR Histogram.
Additionally, the mean(s) and standard deviations are insufficient when
determining the respones behavior. Therefore, this commit also
introduces the output of the 99.x'th percentiles.
=> Integrate High Dynamic Range Histogram

README.md
Hi,
This PR adds a subsection "Dependencies" under the "Install" section in the README to give more details on how to install the dependencies needed to compile Drill.
Most notably the Windows specific instructions on how to install OpenSSL were missing. It is through the error messages of the `openssl-sys` crate's custom build script that I found that Vcpkg was needed along with the package `openssl:x64-windows-static-md`.
Regards 😄
=> [README] Add Linux/macOS/Windows specific instructions

Cargo.lock, Cargo.toml, README.md, SYNTAX.md, example/benchmark.yml, src/benchmark.rs, src/expandable/include.rs, src/expandable/multi_file_request.rs, src/main.rs, src/reader.rs, src/tags.rs
Implemented tags https://github.com/fcsonline/drill/issues/81 
**list-tags**
<pre>
drill --benchmark example/benchmark.yml --list-tags
<font color="#4E9A06">Tags           </font> [&quot;tag_user&quot;]
</pre>
**list-tasks & tags**
<pre>
drill --benchmark example/benchmark.yml --list-tasks --tags tag_user
<font color="#4E9A06">Tags           </font> [&quot;tag_user&quot;]
---
name: Tagged user request
request:
url: /api/users/70
tags:
- tag_user
</pre>
**list-tasks & skip-tags**
<pre>
drill --benchmark example/benchmark.yml --list-tasks --skip-tags tag_user
<font color="#4E9A06">Skip-Tags      </font> [&quot;tag_user&quot;]
---
name: Include comments
include: comments.yml
---
name: Fetch users
request:
url: /api/users.json
---
name: Fetch organizations
request:
url: /api/organizations
--- …
=> Setting tags for skipping and selecting task

.github/workflows/general.yml, example/subtags.yml, example/tags.yml, src/actions/request.rs, src/config.rs, src/expandable/include.rs, src/main.rs, src/reader.rs, src/tags.rs
It seems that items that were included with the `include` directive and contains tags, they are ignored.
Trying to fix this.
Issue:
https://github.com/fcsonline/drill/issues/164
=> Fix tags for included files

src/tags.rs
`cargo clippy` reveals an unnecessary call to `into_iter()` on a `Split`.
We removed unnecessary call to `into_iter()`.
=> fix: Remove unnecessary `into_iter()` after a `split()`

src/interpolator.rs
This PR will close #177 by allowing `$` prefixed keys in a JSON body.
=> fix: Allow `$` prefixed key during interpollation

src/actions/request.rs
Ran into an issue with cookies while trying this out:
- Request 1 would receive Set-Cookie headers for cookies A and B
- Request 2 would receive a Set-Cookie header for only cookie A
- On request 3, the iteration seemed to have forgotten cookie B
Turned out that the whole cookie object was getting replaced when handling each request.
=> Don't overwrite old cookies on Set-Cookie

README.md, SYNTAX.md, src/expandable/multi_iter_request.rs
Closes: #171 
Should I update the examples in the readme or the syntax file?
I originally stumbled across this by following those and expecting it to just work.
=> `pick` for `with items range`
